name: sqljocky
version: 0.3.2
description: >
  A MySQL connector
author: James Ots <code@jamesots.com>
homepage: https://github.com/jamesots/sqljocky
dependencies:
  options_file: ">=0.9.11"
  unittest: ">=0.3.1+1"
  logging: ">=0.3.1+1"
