name: sqljocky
version: 0.5.5
author: James Ots <code@jamesots.com>
description: A MySQL connector
homepage: https://github.com/jamesots/sqljocky
documentation: http://jamesots.github.io/sqljocky/docs
environment:
  sdk: '>=0.5.13'
dependencies:
  crypto: any
  logging: '>=0.3.1+1'
  options_file: '>=0.9.11'
  unittest: '>=0.3.1+1'
