name: sqljocky
version: 0.0.5
description: >
  A MySQL connector
author: James Ots <code@jamesots.com>
homepage: https://github.com/jamesots/sqljocky
dependencies:
  options_file: '>=0.9.2'
  unittest:
    sdk: unittest
  logging:
    sdk: logging
