name: sqljocky
version: 0.4.1
author: James Ots <code@jamesots.com>
description: A MySQL connector
homepage: https://github.com/jamesots/sqljocky
dependencies:
  unittest: '>=0.3.1+1'
  options_file: '>=0.9.11'
  logging: '>=0.3.1+1'
