name: sqljocky
version: 0.0.4
description: >
  A MySQL connector
author: James Ots <code@jamesots.com>
homepage: https://github.com/jamesots/sqljocky
dependencies:
  options_file: any
  unittest:
    sdk: unittest
  logging:
    sdk: logging
