name: sqljocky
version: 0.0.3
description: >
  A MySQL connector
author: James Ots <code@jamesots.com>
homepage: https://github.com/jamesots/sqljocky
dependencies:
  optionsfile: '>=0.9.0'
  unittest:
    sdk: unittest
  logging:
    sdk: logging
