name: sqljocky
version: 0.0.2
description: >
  A MySQL connector
dependencies:
  optionsfile:
    git: git://github.com/jamesots/optionsfile.git
  unittest:
    sdk: unittest
  logging:
    sdk: logging
