name: sqljocky
version: 0.2.0
description: >
  A MySQL connector
author: James Ots <code@jamesots.com>
homepage: https://github.com/jamesots/sqljocky
dependencies:
  options_file: ">=0.9.8"
  unittest: 
    sdk: unittest
  logging: 
    sdk: logging
