name: sqljocky
version: 0.2.0
description: >
  A MySQL connector
author: James Ots <code@jamesots.com>
homepage: https://github.com/jamesots/sqljocky
dependencies:
  options_file: 
    git: git://github.com/jamesots/optionsfile.git
  unittest: 
    sdk: unittest
  logging: 
    sdk: logging
